Iter9
Vova4o/metrix pull request #9
Opened 2024-03-22 12:26 UTC by Vova4o

added flags for the server

2024-03-25 20:34 UTC, rktkov requested changes

2024-03-25 20:34 UTC, rktkov commented on internal/storage/storage.go
> +type StorageInterface interface {
Определять интерфейс стоит в том месте, где он используется. Имя интерфейса стоит сделать отглагольным существительным, например, Storager. Слово интерфейс в именах лучше совсем не использовать.

2024-03-25 20:34 UTC, rktkov commented on internal/storage/memstorage.go
> +func NewMemStorage() *MemStorage {
Возвращаемым аргумент лучше сделать тип интерфейса

2024-03-25 20:34 UTC, rktkov commented on internal/storage/filestorage_test copy.txt
> +package storage
Лишние в репе.

2024-03-25 20:34 UTC, rktkov commented on internal/storage/filestorage.go
> +func NewFileStorage(memStorage *MemStorage, storeInterval int, fileStoragePath string, restore bool) (*FileStorage, error) {
См. комментарий в memstorage

2024-03-25 20:34 UTC, rktkov commented on internal/storage/filestorage.go
> +		case <-quit:
А кто запишет в канал, чтобы сработало это условие?

2024-03-25 20:34 UTC, rktkov commented on internal/handlers/interface.go
> +// func (g GaugeMetricType) GetAll(storage storage.StorageInterface) map[string]string {
Не используемый код лучше удалять.

2024-03-25 20:34 UTC, rktkov commented on internal/handlers/interface.go
> +type MetricType interface {
См. комментарий к интерфейсу хранилища.

2024-03-25 20:34 UTC, rktkov commented on internal/config/config.go
> +package config
Лишний файл.

2024-03-25 20:34 UTC, rktkov commented on internal/MW/mw.go
> +package mw
Лучше пакет назвать  middleware, так будет сразу понятно для чего он нужен.

2024-03-26 03:42 UTC, Vova4o commented on internal/storage/filestorage_test copy.txt
> +package storage
Убрал

2024-03-26 04:22 UTC, Vova4o commented on internal/storage/storage.go
> +type StorageInterface interface {
Я понимаю что лучше его держать в том месте где он используется, но я его пользую почти по всему приложению. Затрудняюсь понять куда лучше его сложить...

2024-03-26 04:22 UTC, Vova4o commented on internal/storage/memstorage.go
> +func NewMemStorage() *MemStorage {
Вроде поменял.

2024-03-26 04:22 UTC, Vova4o commented on internal/storage/filestorage.go
> +func NewFileStorage(memStorage *MemStorage, storeInterval int, fileStoragePath string, restore bool) (*FileStorage, error) {
Как я понял надо вернуть fileStorager interface{} но я не делал его.

2024-03-26 04:22 UTC, Vova4o commented on internal/storage/filestorage.go
> +		case <-quit:
Можно добавить поле quit chan struct{} к файловому хранилищу, и использовать его как отказ от записи в файл, но думаю это приведет к куче лишнего ненужного кода. Кейс просто убрал.

2024-03-26 04:22 UTC, Vova4o commented on internal/handlers/interface.go
> +// func (g GaugeMetricType) GetAll(storage storage.StorageInterface) map[string]string {
Я игрался с кодом видимо оставил на всякий случай.

2024-03-26 04:22 UTC, Vova4o commented on internal/handlers/interface.go
> +type MetricType interface {
Название поменял, оставил на месте так как используется он там же.

2024-03-26 04:22 UTC, Vova4o commented on internal/config/config.go
> +package config
Удалил.

2024-03-26 04:22 UTC, Vova4o commented on internal/MW/mw.go
> +package mw
Переименовал пакет.

2024-04-01 06:00 UTC, rktkov approved these changes

2024-04-02 03:32 UTC, merged